# Generated by Django 3.2.8 on 2021-10-15 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_developerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='developerprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
