# Generated by Django 3.2.8 on 2021-10-15 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import knoct.utils
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_developerprofile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='developer_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(upload_to=knoct.utils.image_upload_to_random)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('phone', models.CharField(blank=True, max_length=32, null=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
            bases=(users.models.UserProxyMixin, models.Model),
        ),
    ]
