# Generated by Django 3.2.8 on 2021-10-15 11:21

from django.db import migrations, models
import knoct.utils


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20211015_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=knoct.utils.image_upload_to_random),
        ),
    ]
